import { AlertCircle, CheckCircle2, Info, TriangleAlert, X } from "lucide-react";
import { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";

const ToastContext=createContext(null);
const CONFIG={success:{icon:CheckCircle2,className:"border-emerald-200 bg-emerald-50 text-emerald-900",iconClass:"text-emerald-600"},error:{icon:AlertCircle,className:"border-red-200 bg-red-50 text-red-900",iconClass:"text-red-600"},warning:{icon:TriangleAlert,className:"border-amber-200 bg-amber-50 text-amber-900",iconClass:"text-amber-600"},info:{icon:Info,className:"border-blue-200 bg-blue-50 text-blue-900",iconClass:"text-blue-600"}};
let sequence=0;
export function ToastProvider({children}){
 const[toasts,setToasts]=useState([]);
 const dismiss=useCallback((id)=>setToasts(current=>current.filter(item=>item.id!==id)),[]);
 const notify=useCallback((message,options={})=>{const id=++sequence;const toast={id,message:String(message||"Notification"),title:options.title||"",type:CONFIG[options.type]?options.type:"info",duration:Number.isFinite(options.duration)?options.duration:5000};setToasts(current=>[...current.slice(-4),toast]);return id;},[]);
 const api=useMemo(()=>({notify,dismiss,success:(message,options={})=>notify(message,{...options,type:"success"}),error:(message,options={})=>notify(message,{...options,type:"error"}),warning:(message,options={})=>notify(message,{...options,type:"warning"}),info:(message,options={})=>notify(message,{...options,type:"info"})}),[dismiss,notify]);
 return <ToastContext.Provider value={api}>{children}{createPortal(<div className="pointer-events-none fixed right-4 top-4 z-[1400] flex w-[min(420px,calc(100vw-2rem))] flex-col gap-3" aria-live="polite" aria-atomic="false">{toasts.map(toast=><Toast key={toast.id} toast={toast} dismiss={dismiss}/>)}</div>,document.body)}</ToastContext.Provider>;
}
function Toast({toast,dismiss}){const config=CONFIG[toast.type];const Icon=config.icon;const timer=useRef(null);const remaining=useRef(toast.duration);const started=useRef(0);const start=useCallback(()=>{if(toast.duration<=0)return;started.current=Date.now();timer.current=setTimeout(()=>dismiss(toast.id),remaining.current);},[dismiss,toast.duration,toast.id]);const pause=useCallback(()=>{if(!timer.current)return;clearTimeout(timer.current);timer.current=null;remaining.current=Math.max(0,remaining.current-(Date.now()-started.current));},[]);useEffect(()=>{start();return()=>clearTimeout(timer.current);},[start]);return <div className={`pointer-events-auto flex items-start gap-3 rounded-2xl border p-4 shadow-2xl backdrop-blur ${config.className}`} role={toast.type==="error"?"alert":"status"} onMouseEnter={pause} onMouseLeave={start} onFocusCapture={pause} onBlurCapture={start}><Icon className={`mt-0.5 h-5 w-5 shrink-0 ${config.iconClass}`}/><div className="min-w-0 flex-1">{toast.title&&<p className="font-bold">{toast.title}</p>}<p className="text-sm leading-5">{toast.message}</p></div><button type="button" onClick={()=>dismiss(toast.id)} className="rounded-lg p-1 opacity-70 hover:bg-white/60 hover:opacity-100" aria-label="Dismiss notification"><X className="h-4 w-4"/></button></div>;}
export function useToast(){const value=useContext(ToastContext);if(!value)throw new Error("useToast must be used within ToastProvider.");return value;}