const pool = require("../db/pool");
const SORT_COLUMNS = Object.freeze({ name:"w.name", code:"w.code", status:"w.status", workspace_type:"w.workspace_type", created_at:"w.created_at", updated_at:"w.updated_at" });
function positiveInteger(value,fallback){const parsed=Number(value);return Number.isInteger(parsed)&&parsed>=0?parsed:fallback;}
async function writeAudit(database, request, action, oldValue, newValue, details={}) {
  try { await database.query(`INSERT INTO administration_audit_log (actor_user_id,target_user_id,action,old_value,new_value,details) VALUES ($1,NULL,$2,$3::jsonb,$4::jsonb,$5::jsonb)`,[request.user.id,action,oldValue==null?null:JSON.stringify(oldValue),newValue==null?null:JSON.stringify(newValue),JSON.stringify(details)]); }
  catch(error){ if(error.code!=="42P01") throw error; }
}
async function listWorkspaces(options={}, user) {
  const limit=Math.min(positiveInteger(options.limit,50),200),offset=positiveInteger(options.offset,0),values=[],where=[];
  const privileged=["manager","admin","superadmin"].includes(user.role);
  if(!privileged){values.push(user.id);where.push(`(w.status='active' OR EXISTS (SELECT 1 FROM workspace_members wm WHERE wm.workspace_id=w.id AND wm.user_id=$${values.length} AND wm.is_active=TRUE))`);}
  if(options.search){values.push(`%${String(options.search).trim()}%`);where.push(`(w.name ILIKE $${values.length} OR w.code ILIKE $${values.length})`);}
  if(options.status){values.push(options.status);where.push(`w.status=$${values.length}`);}
  if(options.workspaceType){values.push(options.workspaceType);where.push(`w.workspace_type=$${values.length}`);}
  if(options.managerUserId){values.push(options.managerUserId);where.push(`w.manager_user_id=$${values.length}`);}
  const clause=where.length?`WHERE ${where.join(" AND ")}`:"";
  const sort=SORT_COLUMNS[options.sortBy]||SORT_COLUMNS.name,direction=String(options.sortDirection).toLowerCase()==="desc"?"DESC":"ASC";
  const count=await pool.query(`SELECT COUNT(*)::int AS total FROM service_workspaces w ${clause}`,values);
  values.push(limit,offset);
  const result=await pool.query(`SELECT w.*,(SELECT COUNT(*)::int FROM workspace_members m WHERE m.workspace_id=w.id AND m.is_active=TRUE) member_count,(SELECT COUNT(*)::int FROM workspace_request_templates t WHERE t.workspace_id=w.id AND t.status<>'archived') template_count FROM service_workspaces w ${clause} ORDER BY ${sort} ${direction},w.id LIMIT $${values.length-1} OFFSET $${values.length}`,values);
  return {items:result.rows,total:count.rows[0].total,limit,offset};
}
async function getWorkspace(id,database=pool){const result=await database.query(`SELECT * FROM service_workspaces WHERE id=$1 LIMIT 1`,[id]);return result.rows[0]||null;}
async function createWorkspace(input,request){const client=await pool.connect();try{await client.query("BEGIN");const result=await client.query(`INSERT INTO service_workspaces(code,name,workspace_type,description,icon_key,colour_key,status,default_group_id,manager_user_id,employee_visibility,settings,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11::jsonb,$12,$12) RETURNING *`,[input.code,input.name,input.workspaceType||"department",input.description||null,input.iconKey||null,input.colourKey||null,input.status||"draft",input.defaultGroupId||null,input.managerUserId||null,JSON.stringify(input.employeeVisibility||{}),JSON.stringify(input.settings||{}),request.user.id]);await writeAudit(client,request,"workspace.created",null,result.rows[0],{workspaceId:result.rows[0].id});await client.query("COMMIT");return result.rows[0];}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
async function updateWorkspace(id,input,request){const client=await pool.connect();try{await client.query("BEGIN");const oldValue=await getWorkspace(id,client);if(!oldValue){await client.query("ROLLBACK");return null;}const merged={...oldValue,...input};const result=await client.query(`UPDATE service_workspaces SET name=$2,description=$3,icon_key=$4,colour_key=$5,manager_user_id=$6,default_group_id=$7,employee_visibility=$8::jsonb,settings=$9::jsonb,updated_by=$10,updated_at=NOW() WHERE id=$1 RETURNING *`,[id,merged.name,merged.description,merged.iconKey??merged.icon_key,merged.colourKey??merged.colour_key,merged.managerUserId??merged.manager_user_id,merged.defaultGroupId??merged.default_group_id,JSON.stringify(merged.employeeVisibility??merged.employee_visibility??{}),JSON.stringify(merged.settings||{}),request.user.id]);await writeAudit(client,request,"workspace.updated",oldValue,result.rows[0],{workspaceId:id});await client.query("COMMIT");return result.rows[0];}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
async function transitionWorkspace(id,status,request){const client=await pool.connect();try{await client.query("BEGIN");const oldValue=await getWorkspace(id,client);if(!oldValue){await client.query("ROLLBACK");return null;}const allowed={draft:["active","archived"],active:["inactive","archived"],inactive:["active","archived"],archived:["inactive"]};if(!allowed[oldValue.status]?.includes(status)){const error=new Error(`Invalid workspace transition from ${oldValue.status} to ${status}.`);error.status=409;throw error;}const result=await client.query(`UPDATE service_workspaces SET status=$2,updated_by=$3,updated_at=NOW() WHERE id=$1 RETURNING *`,[id,status,request.user.id]);await writeAudit(client,request,`workspace.${status}`,oldValue,result.rows[0],{workspaceId:id});await client.query("COMMIT");return result.rows[0];}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
async function dashboard(id,user){const workspace=await getWorkspace(id);if(!workspace)return null;const metrics={openRequests:null,unassignedRequests:null,atRiskRequests:null,slaCompliance:null,averageResolution:null};return {workspace,metrics,availability:{ticketMetrics:false,message:"Workspace ticket linkage will be enabled in the next batch."}};}
module.exports={listWorkspaces,getWorkspace,createWorkspace,updateWorkspace,transitionWorkspace,dashboard};
