import { ArrowLeft, LayoutDashboard, Settings, Users, FileText, Activity } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import WorkspaceShell from "../components/WorkspaceShell";
import { workspacesApi } from "../services/api";

const LABELS={openRequests:"Open Requests",unassignedRequests:"Unassigned",atRiskRequests:"At Risk",slaCompliance:"SLA Compliance",averageResolution:"Average Resolution"};
const STATUS_CLASSES={draft:"bg-amber-100 text-amber-800",active:"bg-emerald-100 text-emerald-800",inactive:"bg-slate-200 text-slate-700",archived:"bg-rose-100 text-rose-700"};
export default function WorkspaceDashboard(){
 const{id}=useParams(),navigate=useNavigate(),[data,setData]=useState(null),[error,setError]=useState("");
 useEffect(()=>{workspacesApi.getDashboard(id).then((response)=>setData(response.data)).catch((requestError)=>setError(requestError.response?.data?.error||requestError.message));},[id]);
 return <WorkspaceShell><main className="h-full overflow-y-auto p-5 xl:p-8"><div className="mx-auto max-w-[1650px]">
  <button type="button" onClick={()=>navigate("/workspaces")} className="btn-secondary mb-4 gap-2 py-2"><ArrowLeft className="h-4 w-4"/>Back to Workspaces</button>
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}
  {!data&&!error&&<div className="rounded-2xl border bg-white p-10 text-center text-slate-500">Loading workspace dashboard...</div>}
  {data&&<><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold text-blue-700"><Link to="/">Dashboard</Link> / <Link to="/workspaces">Workspaces</Link> / {data.workspace.name}</p><div className="mt-2 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-bold text-slate-950">{data.workspace.name} Workspace</h1><span className={`rounded-full px-3 py-1 text-xs font-bold capitalize ${STATUS_CLASSES[data.workspace.status]}`}>{data.workspace.status}</span></div><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">{data.workspace.description}</p></div><div className="flex flex-wrap gap-2"><button className="btn-secondary gap-2"><Users className="h-4 w-4"/>Members</button><button className="btn-secondary gap-2"><FileText className="h-4 w-4"/>Templates</button><button className="btn-primary gap-2"><Settings className="h-4 w-4"/>Workspace Settings</button></div></header>
  <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{Object.entries(data.metrics).map(([key,value])=><article key={key} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm font-semibold text-slate-500">{LABELS[key]||key}</p><p className="mt-2 text-3xl font-bold text-slate-950">{value??"N/A"}</p></article>)}</section>
  <section className="mt-6 grid gap-5 xl:grid-cols-3"><article className="rounded-2xl border bg-white p-6 xl:col-span-2"><div className="flex items-center gap-2"><LayoutDashboard className="h-5 w-5 text-blue-700"/><h2 className="text-lg font-bold">Operational Overview</h2></div><div className="mt-6 rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-10 text-center"><p className="font-bold text-slate-700">Workspace ticket analytics are ready for connection</p><p className="mt-2 text-sm text-slate-500">Ticket-to-workspace linking, category trends and SLA metrics will be enabled in the next batch.</p></div></article><article className="rounded-2xl border bg-white p-6"><div className="flex items-center gap-2"><Activity className="h-5 w-5 text-blue-700"/><h2 className="text-lg font-bold">Workspace Summary</h2></div><dl className="mt-5 space-y-4 text-sm"><div className="flex justify-between"><dt className="text-slate-500">Code</dt><dd className="font-bold">{data.workspace.code}</dd></div><div className="flex justify-between"><dt className="text-slate-500">Type</dt><dd className="font-bold capitalize">{String(data.workspace.workspace_type).replaceAll("_"," ")}</dd></div><div className="flex justify-between"><dt className="text-slate-500">Status</dt><dd className="font-bold capitalize">{data.workspace.status}</dd></div></dl></article></section></>}
 </div></main></WorkspaceShell>;
}