import { ArrowLeft, BriefcaseBusiness, Building2, Plus, Search } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import SmartDataGrid from "../components/data/SmartDataGrid";
import Drawer from "../components/overlays/Drawer";
import Modal from "../components/overlays/Modal";
import WorkspaceShell from "../components/WorkspaceShell";
import { workspacesApi } from "../services/api";

const EMPTY_FORM={name:"",code:"",workspaceType:"department",description:""};
const STATUS_CLASSES={draft:"bg-amber-100 text-amber-800",active:"bg-emerald-100 text-emerald-800",inactive:"bg-slate-200 text-slate-700",archived:"bg-rose-100 text-rose-700"};
function getError(error){return error?.response?.data?.error||error?.message||"The workspace request failed.";}
function Field({label,required,children,hint}){return <label className="block"><span className="text-sm font-bold text-slate-700">{label}{required&&<span className="ml-1 text-red-600">*</span>}</span><div className="mt-2">{children}</div>{hint&&<p className="mt-1 text-xs text-slate-500">{hint}</p>}</label>;}

export default function Workspaces(){
 const navigate=useNavigate();
 const[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[selected,setSelected]=useState(null),[creating,setCreating]=useState(false),[form,setForm]=useState(EMPTY_FORM),[saving,setSaving]=useState(false),[formError,setFormError]=useState("");
 const dirty=Object.values(form).some(Boolean)&&JSON.stringify(form)!==JSON.stringify(EMPTY_FORM);
 const load=async()=>{setLoading(true);setError("");try{const{data}=await workspacesApi.getAll({search,status:status||undefined,limit:100,offset:0});setRows(data.items||[]);}catch(requestError){setError(getError(requestError));}finally{setLoading(false);}};
 useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer);},[search,status]);
 const submit=async(event)=>{event.preventDefault();setFormError("");if(form.name.trim().length<2)return setFormError("Workspace name must contain at least two characters.");if(!/^[A-Z0-9_-]{2,50}$/.test(form.code.trim().toUpperCase()))return setFormError("Workspace code must contain 2-50 letters, numbers, underscores or hyphens.");setSaving(true);try{await workspacesApi.create({...form,name:form.name.trim(),code:form.code.trim().toUpperCase(),description:form.description.trim()});setCreating(false);setForm(EMPTY_FORM);await load();}catch(requestError){setFormError(getError(requestError));}finally{setSaving(false);}};
 const columns=useMemo(()=>[
  {key:"name",label:"Workspace",render:(value,row)=><div className="flex items-center gap-3"><div className="rounded-xl bg-blue-100 p-2 text-blue-700"><Building2 className="h-5 w-5"/></div><div><p className="font-bold text-slate-900">{value}</p><p className="text-xs capitalize text-slate-500">{String(row.workspace_type||"department").replaceAll("_"," ")}</p></div></div>},
  {key:"code",label:"Code",render:(value)=><span className="rounded-lg bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-700">{value}</span>},
  {key:"status",label:"Status",render:(value)=><span className={`rounded-full px-2.5 py-1 text-xs font-bold capitalize ${STATUS_CLASSES[value]||STATUS_CLASSES.draft}`}>{value}</span>},
  {key:"member_count",label:"Members"},{key:"template_count",label:"Templates"}
 ],[]);
 return <WorkspaceShell><main className="flex h-full min-h-0 flex-col overflow-hidden p-5 xl:p-8">
  <header className="mx-auto w-full max-w-[1650px] shrink-0"><button type="button" onClick={()=>navigate("/")} className="btn-secondary mb-4 gap-2 py-2"><ArrowLeft className="h-4 w-4"/>Back to Dashboard</button><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold text-blue-700">Dashboard / Workspaces</p><h1 className="mt-1 text-3xl font-bold text-slate-950">Service Workspaces</h1><p className="mt-2 text-sm text-slate-500">Create and manage departmental service centres for IT, HR, Finance, Facilities and future teams.</p></div><button type="button" onClick={()=>setCreating(true)} className="btn-primary gap-2"><Plus className="h-4 w-4"/>Create Workspace</button></div></header>
  {error&&<div className="mx-auto mt-4 w-full max-w-[1650px] shrink-0 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}
  <section className="mx-auto mt-6 min-h-0 w-full max-w-[1650px] flex-1"><SmartDataGrid title={`${rows.length} Workspaces`} loading={loading} error={error?"":undefined} rows={rows} columns={columns} onRowClick={setSelected} filters={<div className="flex w-full flex-wrap gap-3"><div className="relative min-w-[260px] flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input className="input py-2.5 pl-10" type="search" value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="Search workspaces"/></div><select className="input w-auto min-w-[170px] py-2.5" value={status} onChange={(event)=>setStatus(event.target.value)}><option value="">All statuses</option><option value="draft">Draft</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="archived">Archived</option></select></div>}/></section>
  <Drawer open={!!selected} title={selected?.name||"Workspace"} onClose={()=>setSelected(null)}>{selected&&<div className="space-y-5"><div className="flex items-center gap-3"><div className="rounded-2xl bg-blue-100 p-3 text-blue-700"><BriefcaseBusiness className="h-6 w-6"/></div><div><p className="font-bold text-slate-950">{selected.code}</p><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold capitalize ${STATUS_CLASSES[selected.status]}`}>{selected.status}</span></div></div><p className="text-sm leading-6 text-slate-600">{selected.description||"No description provided."}</p><div className="grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase text-slate-500">Members</p><p className="mt-1 text-2xl font-bold">{selected.member_count||0}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase text-slate-500">Templates</p><p className="mt-1 text-2xl font-bold">{selected.template_count||0}</p></div></div><Link className="btn-primary w-full" to={`/workspaces/${selected.id}`}>Open Workspace Dashboard</Link></div>}</Drawer>
  <Modal open={creating} title="Create Workspace" description="Set up a departmental or shared-service workspace. New workspaces remain in draft until activated." size="large" dirty={dirty} onClose={()=>{setCreating(false);setForm(EMPTY_FORM);setFormError("");}} footer={<><button type="button" onClick={()=>setCreating(false)} disabled={saving} className="btn-secondary">Cancel</button><button type="submit" form="workspace-create-form" disabled={saving} className="btn-primary">{saving?"Saving...":"Save Workspace"}</button></>}><form id="workspace-create-form" onSubmit={submit} className="grid gap-5 md:grid-cols-2">{formError&&<div className="md:col-span-2 rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-semibold text-red-700">{formError}</div>}<Field label="Workspace name" required><input autoFocus className="input" required value={form.name} onChange={(event)=>setForm({...form,name:event.target.value})} placeholder="Example: Procurement"/></Field><Field label="Workspace code" required hint="Use a short unique code such as PROC or HSE."><input className="input uppercase" required maxLength="50" value={form.code} onChange={(event)=>setForm({...form,code:event.target.value.toUpperCase().replace(/[^A-Z0-9_-]/g,"")})} placeholder="PROC"/></Field><Field label="Workspace type"><select className="input" value={form.workspaceType} onChange={(event)=>setForm({...form,workspaceType:event.target.value})}><option value="department">Department</option><option value="operational">Operational</option><option value="shared_service">Shared service</option></select></Field><div className="hidden md:block"/><div className="md:col-span-2"><Field label="Description"><textarea className="input resize-y" rows="4" value={form.description} onChange={(event)=>setForm({...form,description:event.target.value})} placeholder="Describe the services and employees supported by this workspace."/></Field></div></form></Modal>
 </main></WorkspaceShell>;
}