import {Activity,ArrowLeft,CheckCircle2,FileText,LayoutDashboard,Plus,Settings,ShieldAlert,Users,XCircle} from "lucide-react";
import {useCallback,useEffect,useMemo,useState} from "react";
import {Link,useNavigate,useParams} from "react-router-dom";
import Modal from "../components/overlays/Modal";
import WorkspaceShell from "../components/WorkspaceShell";
import WorkspaceCategoriesPanel from "../components/workspaces/WorkspaceCategoriesPanel";
import {useToast} from "../components/notifications/ToastProvider";
import {workspacesApi} from "../services/api";
const TABS=["overview","members","categories","templates","settings","activity"];
const LABELS={openRequests:"Open Requests",unassignedRequests:"Unassigned",atRiskRequests:"At Risk",slaCompliance:"SLA Compliance",averageResolution:"Average Resolution"};
const STATUS_CLASSES={draft:"bg-amber-100 text-amber-800",active:"bg-emerald-100 text-emerald-800",inactive:"bg-slate-200 text-slate-700",archived:"bg-rose-100 text-rose-700"};
const ROLE_CLASSES={manager:"bg-violet-100 text-violet-700",agent:"bg-blue-100 text-blue-700",viewer:"bg-slate-100 text-slate-700"};
function errorMessage(error){return error?.response?.data?.error||error?.message||"The request failed.";}
export default function WorkspaceDashboard(){
 const{id}=useParams(),navigate=useNavigate(),toast=useToast();const[data,setData]=useState(null),[tab,setTab]=useState("overview"),[error,setError]=useState(""),[busy,setBusy]=useState(false),[modal,setModal]=useState(null),[candidates,setCandidates]=useState([]),[candidateSearch,setCandidateSearch]=useState(""),[memberForm,setMemberForm]=useState({userId:"",memberRole:"agent"}),[reason,setReason]=useState("");
 const load=useCallback(async()=>{setError("");try{const response=await workspacesApi.getDashboard(id);setData(response.data);}catch(e){setError(errorMessage(e));}},[id]);useEffect(()=>{load();},[load]);
 useEffect(()=>{if(modal!=="member")return;const timer=setTimeout(async()=>{try{const response=await workspacesApi.getMemberCandidates(id,{search:candidateSearch});setCandidates(response.data||[]);}catch(e){setError(errorMessage(e));}},250);return()=>clearTimeout(timer);},[candidateSearch,id,modal]);
 const counts=useMemo(()=>{const active=(data?.members||[]).filter(item=>item.is_active);return{all:active.length,manager:active.filter(item=>item.member_role==="manager").length,agent:active.filter(item=>item.member_role==="agent").length,viewer:active.filter(item=>item.member_role==="viewer").length};},[data]);
 const run=async(action,successMessage="Changes saved successfully.")=>{setBusy(true);setError("");try{await action();setModal(null);setReason("");toast.success(successMessage);await load();}catch(e){const message=errorMessage(e);toast.error(message);if(!e?.response)setError(message);}finally{setBusy(false);}};
 const statusAction=()=>{const status=data.workspace.status;if(status==="draft")return{label:"Activate Workspace",target:"active"};if(status==="active")return{label:"Deactivate Workspace",target:"inactive"};if(status==="inactive")return{label:"Reactivate Workspace",target:"active"};return{label:"Restore to Draft",target:"draft"};};
 if(!data)return <WorkspaceShell><main className="h-full overflow-y-auto p-5 xl:p-8">{error?<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>:<div className="rounded-2xl border bg-white p-10 text-center text-slate-500">Loading workspace dashboard...</div>}</main></WorkspaceShell>;
 const action=statusAction();
 return <WorkspaceShell><main className="h-full overflow-y-auto p-5 xl:p-8"><div className="mx-auto max-w-[1650px]">
  <button type="button" onClick={()=>navigate("/workspaces")} className="btn-secondary mb-4 gap-2 py-2"><ArrowLeft className="h-4 w-4"/>Back to Workspaces</button>
  {error&&<div className="mb-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}
  <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold text-blue-700"><Link to="/">Dashboard</Link> / <Link to="/workspaces">Workspaces</Link> / {data.workspace.name}</p><div className="mt-2 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-bold text-slate-950">{data.workspace.name} Workspace</h1><span className={`rounded-full px-3 py-1 text-xs font-bold capitalize ${STATUS_CLASSES[data.workspace.status]}`}>{data.workspace.status}</span></div><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">{data.workspace.description}</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>{setReason("");setModal("status");}} className="btn-primary">{action.label}</button>{["draft","inactive"].includes(data.workspace.status)&&<button onClick={()=>{setReason("");setModal("archive");}} className="btn-secondary text-rose-700">Archive</button>}</div></header>
  <nav className="mt-6 flex gap-2 overflow-x-auto border-b border-slate-200">{TABS.map(item=><button key={item} onClick={()=>setTab(item)} className={tab===item?"border-b-2 border-blue-600 px-4 py-3 text-sm font-bold capitalize text-blue-700":"px-4 py-3 text-sm font-bold capitalize text-slate-500 hover:text-slate-900"}>{item==="templates"?"Request Templates":item}</button>)}</nav>
  {tab==="overview"&&<><section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{Object.entries(data.metrics).map(([key,value])=><article key={key} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm font-semibold text-slate-500">{LABELS[key]||key}</p><p className="mt-2 text-3xl font-bold text-slate-950">{value??"N/A"}</p></article>)}</section><section className="mt-6 grid gap-5 xl:grid-cols-3"><article className="rounded-2xl border bg-white p-6 xl:col-span-2"><div className="flex items-center gap-2"><LayoutDashboard className="h-5 w-5 text-blue-700"/><h2 className="text-lg font-bold">Operational Overview</h2></div><div className="mt-6 rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-10 text-center"><p className="font-bold text-slate-700">Workspace ticket analytics are ready for connection</p><p className="mt-2 text-sm text-slate-500">Ticket-to-workspace linking and SLA metrics will be enabled in the ticket operations batch.</p></div></article><article className="rounded-2xl border bg-white p-6"><div className="flex items-center gap-2"><ShieldAlert className="h-5 w-5 text-blue-700"/><h2 className="text-lg font-bold">Activation Readiness</h2></div><div className="mt-5 space-y-3">{data.readiness.checks.map(check=><button key={check.key} onClick={()=>setTab(check.targetTab)} className="flex w-full items-start gap-3 rounded-xl border p-3 text-left hover:bg-slate-50">{check.passed?<CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-emerald-600"/>:<XCircle className="mt-0.5 h-5 w-5 shrink-0 text-rose-600"/>}<span className="text-sm font-semibold">{check.label}</span></button>)}</div></article></section></>}
  {tab==="members"&&<section className="mt-6"><div className="grid gap-4 sm:grid-cols-4">{Object.entries(counts).map(([key,value])=><div key={key} className="rounded-2xl border bg-white p-5"><p className="text-sm capitalize text-slate-500">{key==="all"?"Active members":key}</p><p className="mt-2 text-3xl font-bold">{value}</p></div>)}</div><div className="mt-5 overflow-hidden rounded-2xl border bg-white"><div className="flex items-center justify-between border-b p-5"><div><h2 className="text-lg font-bold">Workspace Members</h2><p className="text-sm text-slate-500">Managers, agents and viewers with explicit workspace access.</p></div><button onClick={()=>setModal("member")} className="btn-primary gap-2"><Plus className="h-4 w-4"/>Add Member</button></div><div className="divide-y">{data.members.length===0?<div className="p-10 text-center text-slate-500">No members are assigned.</div>:data.members.map(member=><div key={member.id} className="grid gap-4 p-5 md:grid-cols-[1fr_160px_220px_auto] md:items-center"><div><p className="font-bold">{member.name}</p><p className="text-sm text-slate-500">{member.email}</p><p className="text-xs text-slate-400">{member.job_title||"No job title"} | {member.department||"No department"}</p></div><span className={`w-fit rounded-full px-2.5 py-1 text-xs font-bold capitalize ${ROLE_CLASSES[member.member_role]}`}>{member.member_role}</span><p className="text-sm text-slate-600">{member.support_groups?.map(group=>group.name).join(", ")||"No active support group"}</p><div className="flex gap-2"><select value={member.member_role} disabled={!member.is_active||busy} onChange={event=>run(()=>workspacesApi.updateMember(id,member.id,{memberRole:event.target.value}),"Member role updated successfully.")} className="input py-2"><option value="manager">Manager</option><option value="agent">Agent</option><option value="viewer">Viewer</option></select>{member.is_active&&<button onClick={()=>{setModal({type:"remove",member});setReason("");}} className="rounded-xl border px-3 py-2 text-sm font-bold text-rose-700">Remove</button>}</div></div>)}</div></div></section>}
  {tab==="categories"&&<WorkspaceCategoriesPanel workspaceId={id} onChanged={load}/>}
  {tab==="templates"&&<Placeholder icon={FileText} title="Request Templates" text="Template lifecycle and the dynamic request form builder are the next implementation section."/>}
  {tab==="settings"&&<Placeholder icon={Settings} title="Workspace Settings" text={`Manager user ID: ${data.workspace.manager_user_id||"Not assigned"}. Default group ID: ${data.workspace.default_group_id||"Not assigned"}.`}/>} 
  {tab==="activity"&&<Placeholder icon={Activity} title="Workspace Activity" text="Lifecycle and membership events are being recorded. The full searchable timeline follows in the Activity section."/>}
  <Modal open={modal==="member"} title="Add Workspace Member" description="Only active person accounts are eligible. Agents must belong to an active support group." onClose={()=>setModal(null)} footer={<><button className="btn-secondary" onClick={()=>setModal(null)}>Cancel</button><button disabled={!memberForm.userId||busy} className="btn-primary" onClick={()=>run(()=>workspacesApi.addMember(id,{userId:Number(memberForm.userId),memberRole:memberForm.memberRole}),"Member added successfully.")}>{busy?"Adding...":"Add Member"}</button></>}><div className="space-y-4"><input className="input" placeholder="Search eligible people" value={candidateSearch} onChange={event=>setCandidateSearch(event.target.value)}/><select className="input" value={memberForm.userId} onChange={event=>setMemberForm({...memberForm,userId:event.target.value})}><option value="">Select a person</option>{candidates.map(person=><option key={person.id} value={person.id}>{person.name} | {person.email}{person.has_active_support_group?"":" | no support group"}</option>)}</select><select className="input" value={memberForm.memberRole} onChange={event=>setMemberForm({...memberForm,memberRole:event.target.value})}><option value="manager">Manager</option><option value="agent">Agent</option><option value="viewer">Viewer</option></select></div></Modal>
  <Modal open={modal==="status"||modal==="archive"} title={modal==="archive"?"Archive Workspace":action.label} description={modal==="archive"?"Only draft or inactive workspaces may be archived.":"Workspace lifecycle actions are audited."} onClose={()=>setModal(null)} footer={<><button className="btn-secondary" onClick={()=>setModal(null)}>Cancel</button><button disabled={busy} className={modal==="archive"?"rounded-xl bg-rose-600 px-5 py-3 text-sm font-bold text-white":"btn-primary"} onClick={()=>run(()=>workspacesApi.changeStatus(id,{status:modal==="archive"?"archived":action.target,reason}),modal==="archive"?"Workspace archived successfully.":"Workspace status updated successfully.")}>{busy?"Updating...":"Confirm"}</button></>}><textarea className="input" rows="4" value={reason} onChange={event=>setReason(event.target.value)} placeholder={modal==="archive"||action.target==="inactive"?"Reason required":"Optional reason"}/></Modal>
  <Modal open={modal?.type==="remove"} title="Remove Workspace Member" description={`Remove ${modal?.member?.name||"this member"} from active workspace access.`} onClose={()=>setModal(null)} footer={<><button className="btn-secondary" onClick={()=>setModal(null)}>Cancel</button><button disabled={busy} className="rounded-xl bg-rose-600 px-5 py-3 text-sm font-bold text-white" onClick={()=>run(()=>workspacesApi.removeMember(id,modal.member.id,reason),"Workspace member removed.")}>{busy?"Removing...":"Remove Member"}</button></>}><textarea className="input" rows="4" value={reason} onChange={event=>setReason(event.target.value)} placeholder="Reason for removing access"/></Modal>
 </div></main></WorkspaceShell>;
}
function Placeholder({icon:Icon,title,text}){return <section className="mt-6 rounded-2xl border bg-white p-8"><div className="flex items-center gap-3"><div className="rounded-xl bg-blue-100 p-3 text-blue-700"><Icon className="h-6 w-6"/></div><div><h2 className="text-xl font-bold">{title}</h2><p className="mt-1 text-sm text-slate-500">{text}</p></div></div></section>;}
